// Static dataset for the remote-combobox demo — 300 popular GitHub repositories
// (captured once from the GitHub search API), bundled so the story needs no live
// backend and Storybook can deploy as a static site (e.g. GitHub Pages). The
// `repos_ffi` mock server filters + paginates this in-memory with a simulated
// latency, standing in for a real `/search/repositories` endpoint. Carries the
// fields the combobox + the custom-item example use (avatar, stars, language).

export interface Repo {
  full_name: string
  owner: string
  avatar_url: string
  stars: number
  description: string
  language: string
}

export const repos: Repo[] = [
  {
    full_name: "codecrafters-io/build-your-own-x",
    owner: "codecrafters-io",
    avatar_url: "https://avatars.githubusercontent.com/u/58904235?v=4",
    stars: 517845,
    description:
      "Master programming by recreating your favorite technologies from scratch.",
    language: "Markdown",
  },
  {
    full_name: "sindresorhus/awesome",
    owner: "sindresorhus",
    avatar_url: "https://avatars.githubusercontent.com/u/170270?v=4",
    stars: 477498,
    description: "😎 Awesome lists about all kinds of interesting topics",
    language: "",
  },
  {
    full_name: "freeCodeCamp/freeCodeCamp",
    owner: "freeCodeCamp",
    avatar_url: "https://avatars.githubusercontent.com/u/9892522?v=4",
    stars: 450006,
    description:
      "freeCodeCamp.org's open-source codebase and curriculum. Learn math, programming, and computer science for free.",
    language: "TypeScript",
  },
  {
    full_name: "public-apis/public-apis",
    owner: "public-apis",
    avatar_url: "https://avatars.githubusercontent.com/u/51121562?v=4",
    stars: 443209,
    description: "A collective list of free APIs",
    language: "Python",
  },
  {
    full_name: "EbookFoundation/free-programming-books",
    owner: "EbookFoundation",
    avatar_url: "https://avatars.githubusercontent.com/u/14127308?v=4",
    stars: 390565,
    description: ":books: Freely available programming books",
    language: "Python",
  },
  {
    full_name: "openclaw/openclaw",
    owner: "openclaw",
    avatar_url: "https://avatars.githubusercontent.com/u/252820863?v=4",
    stars: 379735,
    description:
      "Your own personal AI assistant. Any OS. Any Platform. The lobster way. 🦞 ",
    language: "TypeScript",
  },
  {
    full_name: "nilbuild/developer-roadmap",
    owner: "nilbuild",
    avatar_url: "https://avatars.githubusercontent.com/u/4921183?v=4",
    stars: 357853,
    description:
      "Interactive roadmaps, guides and other educational content to help developers grow in their careers.",
    language: "TypeScript",
  },
  {
    full_name: "donnemartin/system-design-primer",
    owner: "donnemartin",
    avatar_url: "https://avatars.githubusercontent.com/u/5458997?v=4",
    stars: 354115,
    description:
      "Learn how to design large-scale systems. Prep for the system design interview.  Includes Anki flashcards.",
    language: "Python",
  },
  {
    full_name: "jwasham/coding-interview-university",
    owner: "jwasham",
    avatar_url: "https://avatars.githubusercontent.com/u/3771963?v=4",
    stars: 353309,
    description:
      "A complete computer science study plan to become a software engineer.",
    language: "",
  },
  {
    full_name: "vinta/awesome-python",
    owner: "vinta",
    avatar_url: "https://avatars.githubusercontent.com/u/652070?v=4",
    stars: 304024,
    description:
      "An opinionated list of Python frameworks, libraries, tools, and resources",
    language: "Python",
  },
  {
    full_name: "awesome-selfhosted/awesome-selfhosted",
    owner: "awesome-selfhosted",
    avatar_url: "https://avatars.githubusercontent.com/u/24270415?v=4",
    stars: 300314,
    description:
      "A list of Free Software network services and web applications which can be hosted on your own servers",
    language: "",
  },
  {
    full_name: "996icu/996.ICU",
    owner: "996icu",
    avatar_url: "https://avatars.githubusercontent.com/u/48942249?v=4",
    stars: 276306,
    description:
      "Repo for counting stars and contributing. Press F to pay respect to glorious developers.",
    language: "",
  },
  {
    full_name: "practical-tutorials/project-based-learning",
    owner: "practical-tutorials",
    avatar_url: "https://avatars.githubusercontent.com/u/89421154?v=4",
    stars: 270279,
    description: "Curated list of project-based tutorials",
    language: "",
  },
  {
    full_name: "react/react",
    owner: "react",
    avatar_url: "https://avatars.githubusercontent.com/u/102812?v=4",
    stars: 245967,
    description: "The library for web and native user interfaces.",
    language: "JavaScript",
  },
  {
    full_name: "torvalds/linux",
    owner: "torvalds",
    avatar_url: "https://avatars.githubusercontent.com/u/1024025?v=4",
    stars: 237102,
    description: "Linux kernel source tree",
    language: "C",
  },
  {
    full_name: "obra/superpowers",
    owner: "obra",
    avatar_url: "https://avatars.githubusercontent.com/u/45416?v=4",
    stars: 234515,
    description:
      "An agentic skills framework & software development methodology that works.",
    language: "Shell",
  },
  {
    full_name: "trimstray/the-book-of-secret-knowledge",
    owner: "trimstray",
    avatar_url: "https://avatars.githubusercontent.com/u/31127917?v=4",
    stars: 229436,
    description:
      "A collection of inspiring lists, manuals, cheatsheets, blogs, hacks, one-liners, cli/web tools and more.",
    language: "",
  },
  {
    full_name: "TheAlgorithms/Python",
    owner: "TheAlgorithms",
    avatar_url: "https://avatars.githubusercontent.com/u/20487725?v=4",
    stars: 222089,
    description: "All Algorithms implemented in Python",
    language: "Python",
  },
  {
    full_name: "affaan-m/ECC",
    owner: "affaan-m",
    avatar_url: "https://avatars.githubusercontent.com/u/124439313?v=4",
    stars: 218991,
    description:
      "The agent harness performance optimization system. Skills, instincts, memory, security, and research-first development for Claude Code, Code",
    language: "JavaScript",
  },
  {
    full_name: "vuejs/vue",
    owner: "vuejs",
    avatar_url: "https://avatars.githubusercontent.com/u/6128107?v=4",
    stars: 209930,
    description:
      "This is the repo for Vue 2. For Vue 3, go to https://github.com/vuejs/core",
    language: "TypeScript",
  },
  {
    full_name: "ossu/computer-science",
    owner: "ossu",
    avatar_url: "https://avatars.githubusercontent.com/u/14957346?v=4",
    stars: 205107,
    description: "🎓 Path to a free self-taught education in Computer Science!",
    language: "HTML",
  },
  {
    full_name: "NousResearch/hermes-agent",
    owner: "NousResearch",
    avatar_url: "https://avatars.githubusercontent.com/u/134168893?v=4",
    stars: 198543,
    description: "The agent that grows with you",
    language: "Python",
  },
  {
    full_name: "trekhleb/javascript-algorithms",
    owner: "trekhleb",
    avatar_url: "https://avatars.githubusercontent.com/u/3000285?v=4",
    stars: 196104,
    description:
      "📝 Algorithms and data structures implemented in JavaScript with explanations and links to further readings",
    language: "JavaScript",
  },
  {
    full_name: "tensorflow/tensorflow",
    owner: "tensorflow",
    avatar_url: "https://avatars.githubusercontent.com/u/15658638?v=4",
    stars: 195785,
    description: "An Open Source Machine Learning Framework for Everyone",
    language: "C++",
  },
  {
    full_name: "ultraworkers/claw-code",
    owner: "ultraworkers",
    avatar_url: "https://avatars.githubusercontent.com/u/272961631?v=4",
    stars: 194109,
    description:
      "An agent-managed museum exhibit, built in Rust with Gajae-Code / LazyCodex — developed and maintained with no human intervention.",
    language: "Rust",
  },
  {
    full_name: "n8n-io/n8n",
    owner: "n8n-io",
    avatar_url: "https://avatars.githubusercontent.com/u/45487711?v=4",
    stars: 193402,
    description:
      "Fair-code workflow automation platform with native AI capabilities. Combine visual building with custom code, self-host or cloud, 400+ integ",
    language: "TypeScript",
  },
  {
    full_name: "ohmyzsh/ohmyzsh",
    owner: "ohmyzsh",
    avatar_url: "https://avatars.githubusercontent.com/u/22552083?v=4",
    stars: 188161,
    description:
      "🙃   A delightful community-driven (with 2,500+ contributors) framework for managing your zsh configuration. Includes 300+ optional plugins (",
    language: "Shell",
  },
  {
    full_name: "microsoft/vscode",
    owner: "microsoft",
    avatar_url: "https://avatars.githubusercontent.com/u/6154722?v=4",
    stars: 186573,
    description: "Visual Studio Code",
    language: "TypeScript",
  },
  {
    full_name: "Significant-Gravitas/AutoGPT",
    owner: "Significant-Gravitas",
    avatar_url: "https://avatars.githubusercontent.com/u/130738209?v=4",
    stars: 185048,
    description:
      "AutoGPT is the vision of accessible AI for everyone, to use and to build on. Our mission is to provide the tools, so that you can focus on w",
    language: "Python",
  },
  {
    full_name: "CyC2018/CS-Notes",
    owner: "CyC2018",
    avatar_url: "https://avatars.githubusercontent.com/u/36260787?v=4",
    stars: 184584,
    description:
      ":books: 技术面试必备基础知识、Leetcode、计算机操作系统、计算机网络、系统设计",
    language: "",
  },
  {
    full_name: "getify/You-Dont-Know-JS",
    owner: "getify",
    avatar_url: "https://avatars.githubusercontent.com/u/150330?v=4",
    stars: 184539,
    description: "A book series (2 published editions) on the JS language.",
    language: "",
  },
  {
    full_name: "jackfrued/Python-100-Days",
    owner: "jackfrued",
    avatar_url: "https://avatars.githubusercontent.com/u/7474657?v=4",
    stars: 183572,
    description: "Python - 100天从新手到大师",
    language: "Jupyter Notebook",
  },
  {
    full_name: "massgravel/Microsoft-Activation-Scripts",
    owner: "massgravel",
    avatar_url: "https://avatars.githubusercontent.com/u/59795046?v=4",
    stars: 180056,
    description:
      "Open-source Windows and Office activator featuring HWID, Ohook, TSforge, and Online KMS activation methods, along with advanced troubleshoot",
    language: "Batchfile",
  },
  {
    full_name: "DigitalPlatDev/FreeDomain",
    owner: "DigitalPlatDev",
    avatar_url: "https://avatars.githubusercontent.com/u/126394654?v=4",
    stars: 179485,
    description: "DigitalPlat FreeDomain: Free Domain For Everyone",
    language: "HTML",
  },
  {
    full_name: "multica-ai/andrej-karpathy-skills",
    owner: "multica-ai",
    avatar_url: "https://avatars.githubusercontent.com/u/254743058?v=4",
    stars: 179406,
    description:
      "A single CLAUDE.md file to improve Claude Code behavior, derived from Andrej Karpathy's observations on LLM coding pitfalls.",
    language: "",
  },
  {
    full_name: "flutter/flutter",
    owner: "flutter",
    avatar_url: "https://avatars.githubusercontent.com/u/14101776?v=4",
    stars: 177013,
    description:
      "Flutter makes it easy and fast to build beautiful apps for mobile and beyond",
    language: "Dart",
  },
  {
    full_name: "anomalyco/opencode",
    owner: "anomalyco",
    avatar_url: "https://avatars.githubusercontent.com/u/66570915?v=4",
    stars: 176775,
    description: "The open source coding agent.",
    language: "TypeScript",
  },
  {
    full_name: "avelino/awesome-go",
    owner: "avelino",
    avatar_url: "https://avatars.githubusercontent.com/u/31996?v=4",
    stars: 175987,
    description:
      "A curated list of awesome Go frameworks, libraries and software",
    language: "Go",
  },
  {
    full_name: "ollama/ollama",
    owner: "ollama",
    avatar_url: "https://avatars.githubusercontent.com/u/151674099?v=4",
    stars: 174625,
    description:
      "Get up and running with Kimi-K2.6, GLM-5.1, MiniMax, DeepSeek, gpt-oss, Qwen, Gemma and other models.",
    language: "Go",
  },
  {
    full_name: "github/gitignore",
    owner: "github",
    avatar_url: "https://avatars.githubusercontent.com/u/9919?v=4",
    stars: 174519,
    description: "A collection of useful .gitignore templates",
    language: "",
  },
  {
    full_name: "twbs/bootstrap",
    owner: "twbs",
    avatar_url: "https://avatars.githubusercontent.com/u/2918581?v=4",
    stars: 174361,
    description:
      "The most popular HTML, CSS, and JavaScript framework for developing responsive, mobile first projects on the web.",
    language: "MDX",
  },
  {
    full_name: "yt-dlp/yt-dlp",
    owner: "yt-dlp",
    avatar_url: "https://avatars.githubusercontent.com/u/79589310?v=4",
    stars: 172190,
    description: "A feature-rich command-line audio/video downloader",
    language: "Python",
  },
  {
    full_name: "f/prompts.chat",
    owner: "f",
    avatar_url: "https://avatars.githubusercontent.com/u/196477?v=4",
    stars: 163995,
    description:
      "f.k.a. Awesome ChatGPT Prompts. Share, discover, and collect prompts from the community. Free and open source — self-host for your organizat",
    language: "HTML",
  },
  {
    full_name: "AUTOMATIC1111/stable-diffusion-webui",
    owner: "AUTOMATIC1111",
    avatar_url: "https://avatars.githubusercontent.com/u/20920490?v=4",
    stars: 163800,
    description: "Stable Diffusion web UI",
    language: "Python",
  },
  {
    full_name: "521xueweihan/HelloGitHub",
    owner: "521xueweihan",
    avatar_url: "https://avatars.githubusercontent.com/u/8255800?v=4",
    stars: 162156,
    description:
      ":octocat: 分享 GitHub 上有趣、入门级的开源项目。Share interesting, entry-level open source projects on GitHub.",
    language: "Python",
  },
  {
    full_name: "huggingface/transformers",
    owner: "huggingface",
    avatar_url: "https://avatars.githubusercontent.com/u/25720743?v=4",
    stars: 161766,
    description:
      "🤗 Transformers: the model-definition framework for state-of-the-art machine learning models in text, vision, audio, and multimodal models, f",
    language: "Python",
  },
  {
    full_name: "jlevy/the-art-of-command-line",
    owner: "jlevy",
    avatar_url: "https://avatars.githubusercontent.com/u/2058167?v=4",
    stars: 161390,
    description: "Master the command line, in one page",
    language: "",
  },
  {
    full_name: "microsoft/markitdown",
    owner: "microsoft",
    avatar_url: "https://avatars.githubusercontent.com/u/6154722?v=4",
    stars: 156742,
    description:
      "Python tool for converting files and office documents to Markdown.",
    language: "Python",
  },
  {
    full_name: "Snailclimb/JavaGuide",
    owner: "Snailclimb",
    avatar_url: "https://avatars.githubusercontent.com/u/29880145?v=4",
    stars: 156496,
    description:
      "Java 面试 & 后端通用面试指南，覆盖计算机基础、数据库、分布式、高并发、系统设计与 AI 应用开发",
    language: "JavaScript",
  },
  {
    full_name: "anthropics/skills",
    owner: "anthropics",
    avatar_url: "https://avatars.githubusercontent.com/u/76263028?v=4",
    stars: 153311,
    description: "Public repository for Agent Skills",
    language: "Python",
  },
  {
    full_name: "langflow-ai/langflow",
    owner: "langflow-ai",
    avatar_url: "https://avatars.githubusercontent.com/u/85702467?v=4",
    stars: 149892,
    description:
      "Langflow is a powerful tool for building and deploying AI-powered agents and workflows.",
    language: "Python",
  },
  {
    full_name: "airbnb/javascript",
    owner: "airbnb",
    avatar_url: "https://avatars.githubusercontent.com/u/698437?v=4",
    stars: 148090,
    description: "JavaScript Style Guide",
    language: "JavaScript",
  },
  {
    full_name: "langgenius/dify",
    owner: "langgenius",
    avatar_url: "https://avatars.githubusercontent.com/u/127165244?v=4",
    stars: 146010,
    description: "Production-ready platform for agentic workflow development.",
    language: "TypeScript",
  },
  {
    full_name: "Genymobile/scrcpy",
    owner: "Genymobile",
    avatar_url: "https://avatars.githubusercontent.com/u/3427627?v=4",
    stars: 143931,
    description: "Display and control your Android device",
    language: "C",
  },
  {
    full_name: "open-webui/open-webui",
    owner: "open-webui",
    avatar_url: "https://avatars.githubusercontent.com/u/158137808?v=4",
    stars: 142470,
    description:
      "User-friendly AI Interface (Supports Ollama, OpenAI API, ...)",
    language: "Python",
  },
  {
    full_name: "x1xhlol/system-prompts-and-models-of-ai-tools",
    owner: "x1xhlol",
    avatar_url: "https://avatars.githubusercontent.com/u/185671340?v=4",
    stars: 140949,
    description:
      "FULL Augment Code, Claude Code, Cluely, CodeBuddy, Comet, Cursor, Devin AI, Junie, Kiro, Leap.new, Lovable, Manus, NotionAI, Orchids.app, Pe",
    language: "",
  },
  {
    full_name: "ytdl-org/youtube-dl",
    owner: "ytdl-org",
    avatar_url: "https://avatars.githubusercontent.com/u/48381040?v=4",
    stars: 140544,
    description:
      "Command-line program to download videos from YouTube.com and other video sites",
    language: "Python",
  },
  {
    full_name: "yangshun/tech-interview-handbook",
    owner: "yangshun",
    avatar_url: "https://avatars.githubusercontent.com/u/1315101?v=4",
    stars: 140404,
    description:
      "Curated coding interview preparation materials for busy software engineers",
    language: "TypeScript",
  },
  {
    full_name: "vercel/next.js",
    owner: "vercel",
    avatar_url: "https://avatars.githubusercontent.com/u/14985020?v=4",
    stars: 140106,
    description: "The React Framework",
    language: "JavaScript",
  },
  {
    full_name: "langchain-ai/langchain",
    owner: "langchain-ai",
    avatar_url: "https://avatars.githubusercontent.com/u/126733545?v=4",
    stars: 139784,
    description: "The agent engineering platform.",
    language: "Python",
  },
  {
    full_name: "mattpocock/skills",
    owner: "mattpocock",
    avatar_url: "https://avatars.githubusercontent.com/u/28293365?v=4",
    stars: 138687,
    description:
      "Skills for Real Engineers. Straight from my .claude directory.",
    language: "Shell",
  },
  {
    full_name: "firecrawl/firecrawl",
    owner: "firecrawl",
    avatar_url: "https://avatars.githubusercontent.com/u/135057108?v=4",
    stars: 135972,
    description:
      "The API to search, scrape, and interact with the web at scale. 🔥",
    language: "TypeScript",
  },
  {
    full_name: "microsoft/PowerToys",
    owner: "microsoft",
    avatar_url: "https://avatars.githubusercontent.com/u/6154722?v=4",
    stars: 135342,
    description:
      "Microsoft PowerToys is a collection of utilities that supercharge productivity and customization on Windows",
    language: "C",
  },
  {
    full_name: "golang/go",
    owner: "golang",
    avatar_url: "https://avatars.githubusercontent.com/u/4314092?v=4",
    stars: 134849,
    description: "The Go programming language",
    language: "Go",
  },
  {
    full_name: "labuladong/fucking-algorithm",
    owner: "labuladong",
    avatar_url: "https://avatars.githubusercontent.com/u/37220920?v=4",
    stars: 134426,
    description: "Crack LeetCode, not only how, but also why. ",
    language: "Markdown",
  },
  {
    full_name: "anthropics/claude-code",
    owner: "anthropics",
    avatar_url: "https://avatars.githubusercontent.com/u/76263028?v=4",
    stars: 133534,
    description:
      "Claude Code is an agentic coding tool that lives in your terminal, understands your codebase, and helps you code faster by executing routine",
    language: "Python",
  },
  {
    full_name: "Chalarangelo/30-seconds-of-code",
    owner: "Chalarangelo",
    avatar_url: "https://avatars.githubusercontent.com/u/8281875?v=4",
    stars: 128157,
    description: "Coding articles to level up your development skills",
    language: "JavaScript",
  },
  {
    full_name: "krahets/hello-algo",
    owner: "krahets",
    avatar_url: "https://avatars.githubusercontent.com/u/26993056?v=4",
    stars: 127784,
    description:
      "《Hello 算法》：动画图解、一键运行的数据结构与算法教程。支持简中、繁中、English、日本語，提供 Python, Java, C++, C, C#, JS, Go, Swift, Rust, Ruby, Kotlin, TS, Dart 等代码实现",
    language: "Java",
  },
  {
    full_name: "clash-verge-rev/clash-verge-rev",
    owner: "clash-verge-rev",
    avatar_url: "https://avatars.githubusercontent.com/u/152534467?v=4",
    stars: 126895,
    description:
      "A modern GUI client based on Tauri, designed to run in Windows, macOS and Linux for tailored proxy experience",
    language: "TypeScript",
  },
  {
    full_name: "iptv-org/iptv",
    owner: "iptv-org",
    avatar_url: "https://avatars.githubusercontent.com/u/55937028?v=4",
    stars: 126780,
    description:
      "Collection of publicly available IPTV channels from all over the world",
    language: "TypeScript",
  },
  {
    full_name: "react/react-native",
    owner: "react",
    avatar_url: "https://avatars.githubusercontent.com/u/102812?v=4",
    stars: 126047,
    description: "A framework for building native applications using React",
    language: "C++",
  },
  {
    full_name: "excalidraw/excalidraw",
    owner: "excalidraw",
    avatar_url: "https://avatars.githubusercontent.com/u/59452120?v=4",
    stars: 125794,
    description: "Virtual whiteboard for sketching hand-drawn like diagrams",
    language: "TypeScript",
  },
  {
    full_name: "ripienaar/free-for-dev",
    owner: "ripienaar",
    avatar_url: "https://avatars.githubusercontent.com/u/82342?v=4",
    stars: 123268,
    description:
      "A list of SaaS, PaaS and IaaS offerings that have free tiers of interest to devops and infradev",
    language: "HTML",
  },
  {
    full_name: "kubernetes/kubernetes",
    owner: "kubernetes",
    avatar_url: "https://avatars.githubusercontent.com/u/13629408?v=4",
    stars: 123147,
    description: "Production-Grade Container Scheduling and Management",
    language: "Go",
  },
  {
    full_name: "electron/electron",
    owner: "electron",
    avatar_url: "https://avatars.githubusercontent.com/u/13409222?v=4",
    stars: 121704,
    description:
      ":electron: Build cross-platform desktop apps with JavaScript, HTML, and CSS",
    language: "C++",
  },
  {
    full_name: "nodejs/node",
    owner: "nodejs",
    avatar_url: "https://avatars.githubusercontent.com/u/9950313?v=4",
    stars: 117885,
    description: "Node.js JavaScript runtime ✨🐢🚀✨",
    language: "JavaScript",
  },
  {
    full_name: "Comfy-Org/ComfyUI",
    owner: "Comfy-Org",
    avatar_url: "https://avatars.githubusercontent.com/u/166579949?v=4",
    stars: 117738,
    description:
      "The most powerful and modular diffusion model GUI, api and backend with a graph/nodes interface.",
    language: "Python",
  },
  {
    full_name: "ggml-org/llama.cpp",
    owner: "ggml-org",
    avatar_url: "https://avatars.githubusercontent.com/u/134263123?v=4",
    stars: 117495,
    description: "LLM inference in C/C++",
    language: "C++",
  },
  {
    full_name: "justjavac/free-programming-books-zh_CN",
    owner: "justjavac",
    avatar_url: "https://avatars.githubusercontent.com/u/359395?v=4",
    stars: 117149,
    description: ":books: 免费的计算机编程类中文书籍，欢迎投稿",
    language: "",
  },
  {
    full_name: "shadcn-ui/ui",
    owner: "shadcn-ui",
    avatar_url: "https://avatars.githubusercontent.com/u/139895814?v=4",
    stars: 117061,
    description:
      "A set of beautifully-designed, accessible components and a code distribution platform. Works with your favorite frameworks. Open Source. Ope",
    language: "TypeScript",
  },
  {
    full_name: "rustdesk/rustdesk",
    owner: "rustdesk",
    avatar_url: "https://avatars.githubusercontent.com/u/71636191?v=4",
    stars: 116582,
    description:
      "An open-source remote desktop application designed for self-hosting, as an alternative to TeamViewer.",
    language: "Rust",
  },
  {
    full_name: "Shubhamsaboo/awesome-llm-apps",
    owner: "Shubhamsaboo",
    avatar_url: "https://avatars.githubusercontent.com/u/31396011?v=4",
    stars: 115196,
    description:
      "100+ AI Agent & RAG apps you can actually run — clone, customize, ship.",
    language: "Python",
  },
  {
    full_name: "msitarzewski/agency-agents",
    owner: "msitarzewski",
    avatar_url: "https://avatars.githubusercontent.com/u/1972242?v=4",
    stars: 114777,
    description:
      "A complete AI agency at your fingertips - From frontend wizards to Reddit community ninjas, from whimsy injectors to reality checkers. Each ",
    language: "Shell",
  },
  {
    full_name: "Hack-with-Github/Awesome-Hacking",
    owner: "Hack-with-Github",
    avatar_url: "https://avatars.githubusercontent.com/u/18143746?v=4",
    stars: 114753,
    description:
      "A collection of various awesome lists for hackers, pentesters and security researchers",
    language: "",
  },
  {
    full_name: "github/spec-kit",
    owner: "github",
    avatar_url: "https://avatars.githubusercontent.com/u/9919?v=4",
    stars: 114453,
    description:
      "💫 Toolkit to help you get started with Spec-Driven Development",
    language: "Python",
  },
  {
    full_name: "rust-lang/rust",
    owner: "rust-lang",
    avatar_url: "https://avatars.githubusercontent.com/u/5430905?v=4",
    stars: 113995,
    description:
      "Empowering everyone to build reliable and efficient software.",
    language: "Rust",
  },
  {
    full_name: "mrdoob/three.js",
    owner: "mrdoob",
    avatar_url: "https://avatars.githubusercontent.com/u/97088?v=4",
    stars: 113195,
    description: "JavaScript 3D Library.",
    language: "JavaScript",
  },
  {
    full_name: "d3/d3",
    owner: "d3",
    avatar_url: "https://avatars.githubusercontent.com/u/1562726?v=4",
    stars: 113110,
    description:
      "Bring data to life with SVG, Canvas and HTML. :bar_chart::chart_with_upwards_trend::tada:",
    language: "Shell",
  },
  {
    full_name: "godotengine/godot",
    owner: "godotengine",
    avatar_url: "https://avatars.githubusercontent.com/u/6318500?v=4",
    stars: 112848,
    description: "Godot Engine – Multi-platform 2D and 3D game engine",
    language: "C++",
  },
  {
    full_name: "microsoft/generative-ai-for-beginners",
    owner: "microsoft",
    avatar_url: "https://avatars.githubusercontent.com/u/6154722?v=4",
    stars: 112179,
    description: "21 Lessons, Get Started Building with Generative AI ",
    language: "Jupyter Notebook",
  },
  {
    full_name: "garrytan/gstack",
    owner: "garrytan",
    avatar_url: "https://avatars.githubusercontent.com/u/19957?v=4",
    stars: 112072,
    description:
      "Use Garry Tan's exact Claude Code setup: 23 opinionated tools that serve as CEO, Designer, Eng Manager, Release Manager, Doc Engineer, and Q",
    language: "TypeScript",
  },
  {
    full_name: "2dust/v2rayN",
    owner: "2dust",
    avatar_url: "https://avatars.githubusercontent.com/u/31833384?v=4",
    stars: 109560,
    description:
      "A GUI client for Windows, Linux and macOS, support Xray and sing-box and others",
    language: "C#",
  },
  {
    full_name: "microsoft/TypeScript",
    owner: "microsoft",
    avatar_url: "https://avatars.githubusercontent.com/u/6154722?v=4",
    stars: 109345,
    description:
      "TypeScript is a superset of JavaScript that compiles to clean JavaScript output.",
    language: "TypeScript",
  },
  {
    full_name: "axios/axios",
    owner: "axios",
    avatar_url: "https://avatars.githubusercontent.com/u/32372333?v=4",
    stars: 109082,
    description: "Promise based HTTP client for the browser and node.js",
    language: "JavaScript",
  },
  {
    full_name: "GrowingGit/GitHub-Chinese-Top-Charts",
    owner: "GrowingGit",
    avatar_url: "https://avatars.githubusercontent.com/u/21018904?v=4",
    stars: 108457,
    description:
      ":cn: GitHub中文排行榜，各语言分设「软件 | 资料」榜单，精准定位中文好项目。各取所需，高效学习。",
    language: "Java",
  },
  {
    full_name: "tauri-apps/tauri",
    owner: "tauri-apps",
    avatar_url: "https://avatars.githubusercontent.com/u/54536011?v=4",
    stars: 108142,
    description:
      "Build smaller, faster, and more secure desktop and mobile applications with a web frontend.",
    language: "Rust",
  },
  {
    full_name: "fatedier/frp",
    owner: "fatedier",
    avatar_url: "https://avatars.githubusercontent.com/u/7346661?v=4",
    stars: 107464,
    description:
      "A fast reverse proxy to help you expose a local server behind a NAT or firewall to the internet.",
    language: "Go",
  },
  {
    full_name: "papers-we-love/papers-we-love",
    owner: "papers-we-love",
    avatar_url: "https://avatars.githubusercontent.com/u/6187757?v=4",
    stars: 107205,
    description:
      "Papers from the computer science community to read and discuss.",
    language: "Shell",
  },
  {
    full_name: "denoland/deno",
    owner: "denoland",
    avatar_url: "https://avatars.githubusercontent.com/u/42048915?v=4",
    stars: 107167,
    description: "A modern runtime for JavaScript and TypeScript.",
    language: "Rust",
  },
  {
    full_name: "jaywcjlove/awesome-mac",
    owner: "jaywcjlove",
    avatar_url: "https://avatars.githubusercontent.com/u/1680273?v=4",
    stars: 106056,
    description:
      " This project is dedicated to collecting high-quality macOS software and organizing them systematically by different categories for easy se",
    language: "Swift",
  },
  {
    full_name: "google-gemini/gemini-cli",
    owner: "google-gemini",
    avatar_url: "https://avatars.githubusercontent.com/u/161781182?v=4",
    stars: 105458,
    description:
      "An open-source AI agent that brings the power of Gemini directly into your terminal.",
    language: "TypeScript",
  },
  {
    full_name: "farion1231/cc-switch",
    owner: "farion1231",
    avatar_url: "https://avatars.githubusercontent.com/u/44939412?v=4",
    stars: 105396,
    description:
      "A cross-platform desktop All-in-One assistant for Claude Code, Codex, OpenCode, OpenClaw, Gemini CLI & Hermes Agent. Only official website: ",
    language: "Rust",
  },
  {
    full_name: "goldbergyoni/nodebestpractices",
    owner: "goldbergyoni",
    avatar_url: "https://avatars.githubusercontent.com/u/8571500?v=4",
    stars: 105350,
    description: "✅ The Node.js best practices list (July 2026)",
    language: "Dockerfile",
  },
  {
    full_name: "supabase/supabase",
    owner: "supabase",
    avatar_url: "https://avatars.githubusercontent.com/u/54469796?v=4",
    stars: 104582,
    description:
      "The Postgres development platform. Supabase gives you a dedicated Postgres database to build your web, mobile, and AI applications.",
    language: "TypeScript",
  },
  {
    full_name: "immich-app/immich",
    owner: "immich-app",
    avatar_url: "https://avatars.githubusercontent.com/u/109746326?v=4",
    stars: 103966,
    description:
      "High performance self-hosted photo and video management solution.",
    language: "TypeScript",
  },
  {
    full_name: "deepseek-ai/DeepSeek-V3",
    owner: "deepseek-ai",
    avatar_url: "https://avatars.githubusercontent.com/u/148330874?v=4",
    stars: 103788,
    description: "",
    language: "Python",
  },
  {
    full_name: "microsoft/terminal",
    owner: "microsoft",
    avatar_url: "https://avatars.githubusercontent.com/u/6154722?v=4",
    stars: 103663,
    description:
      "The new Windows Terminal and the original Windows console host, all in the same place!",
    language: "C++",
  },
  {
    full_name: "react/create-react-app",
    owner: "react",
    avatar_url: "https://avatars.githubusercontent.com/u/102812?v=4",
    stars: 103319,
    description: "Set up a modern web app by running one command.",
    language: "JavaScript",
  },
  {
    full_name: "openai/whisper",
    owner: "openai",
    avatar_url: "https://avatars.githubusercontent.com/u/14957082?v=4",
    stars: 103240,
    description: "Robust Speech Recognition via Large-Scale Weak Supervision",
    language: "Python",
  },
  {
    full_name: "pytorch/pytorch",
    owner: "pytorch",
    avatar_url: "https://avatars.githubusercontent.com/u/21003710?v=4",
    stars: 100915,
    description:
      "Tensors and Dynamic neural networks in Python with strong GPU acceleration",
    language: "Python",
  },
  {
    full_name: "Anduin2017/HowToCook",
    owner: "Anduin2017",
    avatar_url: "https://avatars.githubusercontent.com/u/19531547?v=4",
    stars: 100869,
    description: "Programmer's guide about how to cook at home.",
    language: "",
  },
  {
    full_name: "neovim/neovim",
    owner: "neovim",
    avatar_url: "https://avatars.githubusercontent.com/u/6471485?v=4",
    stars: 100571,
    description: "Vim-fork focused on extensibility and usability",
    language: "Vim Script",
  },
  {
    full_name: "angular/angular",
    owner: "angular",
    avatar_url: "https://avatars.githubusercontent.com/u/139426?v=4",
    stars: 100389,
    description: "Deliver web apps with confidence 🚀",
    language: "TypeScript",
  },
  {
    full_name: "mtdvio/every-programmer-should-know",
    owner: "mtdvio",
    avatar_url: "https://avatars.githubusercontent.com/u/33053074?v=4",
    stars: 99872,
    description:
      "A collection of (mostly) technical things every software developer should know about",
    language: "",
  },
  {
    full_name: "browser-use/browser-use",
    owner: "browser-use",
    avatar_url: "https://avatars.githubusercontent.com/u/192012301?v=4",
    stars: 99803,
    description:
      "🌐 Make websites accessible for AI agents. Automate tasks online with ease.",
    language: "Python",
  },
  {
    full_name: "fastapi/fastapi",
    owner: "fastapi",
    avatar_url: "https://avatars.githubusercontent.com/u/156354296?v=4",
    stars: 99448,
    description:
      "FastAPI framework, high performance, easy to learn, fast to code, ready for production",
    language: "Python",
  },
  {
    full_name: "mui/material-ui",
    owner: "mui",
    avatar_url: "https://avatars.githubusercontent.com/u/33663932?v=4",
    stars: 98439,
    description:
      "Material UI: Comprehensive React component library that implements Google's Material Design. Free forever.",
    language: "JavaScript",
  },
  {
    full_name: "ant-design/ant-design",
    owner: "ant-design",
    avatar_url: "https://avatars.githubusercontent.com/u/12101536?v=4",
    stars: 98407,
    description: "An enterprise-class UI design language and React UI library",
    language: "TypeScript",
  },
  {
    full_name: "rasbt/LLMs-from-scratch",
    owner: "rasbt",
    avatar_url: "https://avatars.githubusercontent.com/u/5618407?v=4",
    stars: 97471,
    description:
      "Implement a ChatGPT-like LLM in PyTorch from scratch, step by step",
    language: "Jupyter Notebook",
  },
  {
    full_name: "nvbn/thefuck",
    owner: "nvbn",
    avatar_url: "https://avatars.githubusercontent.com/u/1114542?v=4",
    stars: 97396,
    description:
      "Magnificent app which corrects your previous console command.",
    language: "Python",
  },
  {
    full_name: "microsoft/Web-Dev-For-Beginners",
    owner: "microsoft",
    avatar_url: "https://avatars.githubusercontent.com/u/6154722?v=4",
    stars: 95883,
    description: "24 Lessons, 12 Weeks, Get Started as a Web Developer",
    language: "JavaScript",
  },
  {
    full_name: "tailwindlabs/tailwindcss",
    owner: "tailwindlabs",
    avatar_url: "https://avatars.githubusercontent.com/u/67109815?v=4",
    stars: 95666,
    description: "A utility-first CSS framework for rapid UI development.",
    language: "TypeScript",
  },
  {
    full_name: "puppeteer/puppeteer",
    owner: "puppeteer",
    avatar_url: "https://avatars.githubusercontent.com/u/6906516?v=4",
    stars: 95173,
    description: "JavaScript API for Chrome and Firefox",
    language: "TypeScript",
  },
  {
    full_name: "florinpop17/app-ideas",
    owner: "florinpop17",
    avatar_url: "https://avatars.githubusercontent.com/u/6692364?v=4",
    stars: 95142,
    description:
      "A Collection of application ideas which can be used to improve your coding skills.",
    language: "",
  },
  {
    full_name: "nextlevelbuilder/ui-ux-pro-max-skill",
    owner: "nextlevelbuilder",
    avatar_url: "https://avatars.githubusercontent.com/u/246974152?v=4",
    stars: 94499,
    description:
      "An AI SKILL that provide design intelligence for building professional UI/UX multiple platforms",
    language: "Python",
  },
  {
    full_name: "ryanmcdermott/clean-code-javascript",
    owner: "ryanmcdermott",
    avatar_url: "https://avatars.githubusercontent.com/u/5114666?v=4",
    stars: 94451,
    description: "Clean Code concepts adapted for JavaScript",
    language: "JavaScript",
  },
  {
    full_name: "ruanyf/weekly",
    owner: "ruanyf",
    avatar_url: "https://avatars.githubusercontent.com/u/905434?v=4",
    stars: 94198,
    description: "科技爱好者周刊，每周五发布",
    language: "",
  },
  {
    full_name: "iluwatar/java-design-patterns",
    owner: "iluwatar",
    avatar_url: "https://avatars.githubusercontent.com/u/582346?v=4",
    stars: 94136,
    description: "Design patterns implemented in Java",
    language: "Java",
  },
  {
    full_name: "hacksider/Deep-Live-Cam",
    owner: "hacksider",
    avatar_url: "https://avatars.githubusercontent.com/u/1267200?v=4",
    stars: 94023,
    description:
      "real time face swap and one-click video deepfake with only a single image",
    language: "Python",
  },
  {
    full_name: "nvm-sh/nvm",
    owner: "nvm-sh",
    avatar_url: "https://avatars.githubusercontent.com/u/49963700?v=4",
    stars: 93885,
    description:
      "Node Version Manager - POSIX-compliant bash script to manage multiple active node.js versions",
    language: "Shell",
  },
  {
    full_name: "oven-sh/bun",
    owner: "oven-sh",
    avatar_url: "https://avatars.githubusercontent.com/u/108928776?v=4",
    stars: 93335,
    description:
      "Incredibly fast JavaScript runtime, bundler, test runner, and package manager – all in one",
    language: "Rust",
  },
  {
    full_name: "openai/codex",
    owner: "openai",
    avatar_url: "https://avatars.githubusercontent.com/u/14957082?v=4",
    stars: 92382,
    description: "Lightweight coding agent that runs in your terminal",
    language: "Rust",
  },
  {
    full_name: "deepseek-ai/DeepSeek-R1",
    owner: "deepseek-ai",
    avatar_url: "https://avatars.githubusercontent.com/u/148330874?v=4",
    stars: 91986,
    description: "",
    language: "",
  },
  {
    full_name: "VoltAgent/awesome-design-md",
    owner: "VoltAgent",
    avatar_url: "https://avatars.githubusercontent.com/u/201282378?v=4",
    stars: 91939,
    description:
      "A collection of DESIGN.md files analysis by popular brand design systems. Drop one into your project and let coding agents generate a matchi",
    language: "",
  },
  {
    full_name: "microsoft/playwright",
    owner: "microsoft",
    avatar_url: "https://avatars.githubusercontent.com/u/6154722?v=4",
    stars: 91327,
    description:
      "Playwright is a framework for Web Testing and Automation. It allows testing Chromium, Firefox and WebKit with a single API. ",
    language: "TypeScript",
  },
  {
    full_name: "harry0703/MoneyPrinterTurbo",
    owner: "harry0703",
    avatar_url: "https://avatars.githubusercontent.com/u/4928832?v=4",
    stars: 90503,
    description:
      "利用AI大模型，一键生成高清短视频 Generate short videos with one click using AI LLM.",
    language: "Python",
  },
  {
    full_name: "storybookjs/storybook",
    owner: "storybookjs",
    avatar_url: "https://avatars.githubusercontent.com/u/22632046?v=4",
    stars: 90395,
    description:
      "Storybook is the industry standard workshop for building, documenting, and testing UI components in isolation",
    language: "TypeScript",
  },
  {
    full_name: "PanJiaChen/vue-element-admin",
    owner: "PanJiaChen",
    avatar_url: "https://avatars.githubusercontent.com/u/8121621?v=4",
    stars: 90256,
    description:
      ":tada: A magical vue admin                                                                https://panjiachen.github.io/vue-element-admin",
    language: "Vue",
  },
  {
    full_name: "punkpeye/awesome-mcp-servers",
    owner: "punkpeye",
    avatar_url: "https://avatars.githubusercontent.com/u/108313943?v=4",
    stars: 89541,
    description: "A collection of MCP servers.",
    language: "",
  },
  {
    full_name: "bitcoin/bitcoin",
    owner: "bitcoin",
    avatar_url: "https://avatars.githubusercontent.com/u/528860?v=4",
    stars: 89500,
    description: "Bitcoin Core integration/staging tree",
    language: "C++",
  },
  {
    full_name: "opencv/opencv",
    owner: "opencv",
    avatar_url: "https://avatars.githubusercontent.com/u/5009934?v=4",
    stars: 89296,
    description: "Open Source Computer Vision Library",
    language: "C++",
  },
  {
    full_name: "mermaid-js/mermaid",
    owner: "mermaid-js",
    avatar_url: "https://avatars.githubusercontent.com/u/57169982?v=4",
    stars: 88745,
    description:
      "Generation of diagrams like flowcharts or sequence diagrams from text in a similar manner as markdown",
    language: "TypeScript",
  },
  {
    full_name: "gin-gonic/gin",
    owner: "gin-gonic",
    avatar_url: "https://avatars.githubusercontent.com/u/7894478?v=4",
    stars: 88716,
    description:
      "Gin is a high-performance HTTP web framework written in Go. It provides a Martini-like API but with significantly better performance—up to 4",
    language: "Go",
  },
  {
    full_name: "gohugoio/hugo",
    owner: "gohugoio",
    avatar_url: "https://avatars.githubusercontent.com/u/29385237?v=4",
    stars: 88670,
    description: "The world’s fastest framework for building websites.",
    language: "Go",
  },
  {
    full_name: "ChatGPTNextWeb/NextChat",
    owner: "ChatGPTNextWeb",
    avatar_url: "https://avatars.githubusercontent.com/u/153288546?v=4",
    stars: 88274,
    description:
      "✨ Light and Fast AI Assistant. Support: Web | iOS | MacOS | Android |  Linux | Windows",
    language: "TypeScript",
  },
  {
    full_name: "louislam/uptime-kuma",
    owner: "louislam",
    avatar_url: "https://avatars.githubusercontent.com/u/1336778?v=4",
    stars: 88268,
    description: "A fancy self-hosted monitoring tool",
    language: "JavaScript",
  },
  {
    full_name: "django/django",
    owner: "django",
    avatar_url: "https://avatars.githubusercontent.com/u/27804?v=4",
    stars: 87918,
    description: "The Web framework for perfectionists with deadlines.",
    language: "Python",
  },
  {
    full_name: "home-assistant/core",
    owner: "home-assistant",
    avatar_url: "https://avatars.githubusercontent.com/u/13844975?v=4",
    stars: 87881,
    description:
      ":house_with_garden: Open source home automation that puts local control and privacy first.",
    language: "Python",
  },
  {
    full_name: "karpathy/autoresearch",
    owner: "karpathy",
    avatar_url: "https://avatars.githubusercontent.com/u/241138?v=4",
    stars: 87837,
    description:
      "AI agents running research on single-GPU nanochat training automatically",
    language: "Python",
  },
  {
    full_name: "3b1b/manim",
    owner: "3b1b",
    avatar_url: "https://avatars.githubusercontent.com/u/11601040?v=4",
    stars: 87772,
    description: "Animation engine for explanatory math videos",
    language: "Python",
  },
  {
    full_name: "TauricResearch/TradingAgents",
    owner: "TauricResearch",
    avatar_url: "https://avatars.githubusercontent.com/u/192884433?v=4",
    stars: 87704,
    description: "TradingAgents: Multi-Agents LLM Financial Trading Framework",
    language: "Python",
  },
  {
    full_name: "modelcontextprotocol/servers",
    owner: "modelcontextprotocol",
    avatar_url: "https://avatars.githubusercontent.com/u/182288589?v=4",
    stars: 87505,
    description: "Model Context Protocol Servers",
    language: "TypeScript",
  },
  {
    full_name: "sveltejs/svelte",
    owner: "sveltejs",
    avatar_url: "https://avatars.githubusercontent.com/u/23617963?v=4",
    stars: 87330,
    description: "web development for the rest of us",
    language: "JavaScript",
  },
  {
    full_name: "microsoft/ML-For-Beginners",
    owner: "microsoft",
    avatar_url: "https://avatars.githubusercontent.com/u/6154722?v=4",
    stars: 87114,
    description:
      "12 weeks, 26 lessons, 52 quizzes, classic Machine Learning for all",
    language: "Jupyter Notebook",
  },
  {
    full_name: "MunGell/awesome-for-beginners",
    owner: "MunGell",
    avatar_url: "https://avatars.githubusercontent.com/u/812976?v=4",
    stars: 86702,
    description: "A list of awesome beginners-friendly projects.",
    language: "",
  },
  {
    full_name: "astral-sh/uv",
    owner: "astral-sh",
    avatar_url: "https://avatars.githubusercontent.com/u/115962839?v=4",
    stars: 86607,
    description:
      "An extremely fast Python package and project manager, written in Rust.",
    language: "Rust",
  },
  {
    full_name: "zed-industries/zed",
    owner: "zed-industries",
    avatar_url: "https://avatars.githubusercontent.com/u/79345384?v=4",
    stars: 85673,
    description:
      "Code at the speed of thought – Zed is a high-performance, multiplayer code editor from the creators of Atom and Tree-sitter.",
    language: "Rust",
  },
  {
    full_name: "syncthing/syncthing",
    owner: "syncthing",
    avatar_url: "https://avatars.githubusercontent.com/u/7628018?v=4",
    stars: 85592,
    description: "Open Source Continuous File Synchronization",
    language: "Go",
  },
  {
    full_name: "sherlock-project/sherlock",
    owner: "sherlock-project",
    avatar_url: "https://avatars.githubusercontent.com/u/48293496?v=4",
    stars: 85248,
    description:
      "Hunt down social media accounts by username across social networks",
    language: "Python",
  },
  {
    full_name: "laravel/laravel",
    owner: "laravel",
    avatar_url: "https://avatars.githubusercontent.com/u/958072?v=4",
    stars: 84532,
    description:
      "Laravel is a web application framework with expressive, elegant syntax. We’ve already laid the foundation for your next big idea — freeing y",
    language: "Blade",
  },
  {
    full_name: "macrozheng/mall",
    owner: "macrozheng",
    avatar_url: "https://avatars.githubusercontent.com/u/15903809?v=4",
    stars: 83886,
    description:
      "mall项目是一套电商系统，包括前台商城系统及后台管理系统，基于Spring Boot+MyBatis实现，采用Docker容器化部署。 前台商城系统包含首页门户、商品推荐、商品搜索、商品展示、购物车、订单流程、会员中心、客户服务、帮助中心等模块。 后台管理系统包含商品管理、订单",
    language: "Java",
  },
  {
    full_name: "localsend/localsend",
    owner: "localsend",
    avatar_url: "https://avatars.githubusercontent.com/u/120677616?v=4",
    stars: 83808,
    description: "An open-source cross-platform alternative to AirDrop",
    language: "Dart",
  },
  {
    full_name: "realworld-apps/realworld",
    owner: "realworld-apps",
    avatar_url: "https://avatars.githubusercontent.com/u/245012214?v=4",
    stars: 83645,
    description:
      '"The mother of all demo apps" — Exemplary fullstack Medium.com clone powered by React, Angular, Node, Django, and many more',
    language: "TypeScript",
  },
  {
    full_name: "ByteByteGoHq/system-design-101",
    owner: "ByteByteGoHq",
    avatar_url: "https://avatars.githubusercontent.com/u/120689636?v=4",
    stars: 83595,
    description:
      "Explain complex systems using visuals and simple terms. Help you prepare for system design interviews.",
    language: "",
  },
  {
    full_name: "thedotmack/claude-mem",
    owner: "thedotmack",
    avatar_url: "https://avatars.githubusercontent.com/u/683968?v=4",
    stars: 83466,
    description:
      "Persistent Context Across Sessions for Every Agent –  Captures everything your agent does during sessions, compresses it with AI, and inject",
    language: "JavaScript",
  },
  {
    full_name: "vllm-project/vllm",
    owner: "vllm-project",
    avatar_url: "https://avatars.githubusercontent.com/u/136984999?v=4",
    stars: 83445,
    description:
      "A high-throughput and memory-efficient inference and serving engine for LLMs",
    language: "Python",
  },
  {
    full_name: "infiniflow/ragflow",
    owner: "infiniflow",
    avatar_url: "https://avatars.githubusercontent.com/u/69962740?v=4",
    stars: 83266,
    description:
      "RAGFlow is a leading open-source Retrieval-Augmented Generation (RAG) engine that fuses cutting-edge RAG with Agent capabilities to create a",
    language: "Python",
  },
  {
    full_name: "DopplerHQ/awesome-interview-questions",
    owner: "DopplerHQ",
    avatar_url: "https://avatars.githubusercontent.com/u/34022344?v=4",
    stars: 83193,
    description:
      ":octocat: A curated awesome list of lists of interview questions. Feel free to contribute! :mortar_board: ",
    language: "",
  },
  {
    full_name: "PaddlePaddle/PaddleOCR",
    owner: "PaddlePaddle",
    avatar_url: "https://avatars.githubusercontent.com/u/23534030?v=4",
    stars: 83161,
    description:
      "Turn any PDF or image document into structured data for your AI. A powerful, lightweight OCR toolkit that bridges the gap between images/PDF",
    language: "Python",
  },
  {
    full_name: "bregman-arie/devops-exercises",
    owner: "bregman-arie",
    avatar_url: "https://avatars.githubusercontent.com/u/10349437?v=4",
    stars: 82845,
    description:
      "Linux, Jenkins, AWS, SRE, Prometheus, Docker, Python, Ansible, Git, Kubernetes, Terraform, OpenStack, SQL, NoSQL, Azure, GCP, DNS, Elastic, ",
    language: "Python",
  },
  {
    full_name: "animate-css/animate.css",
    owner: "animate-css",
    avatar_url: "https://avatars.githubusercontent.com/u/64791939?v=4",
    stars: 82620,
    description:
      "🍿 A cross-browser library of CSS animations. As easy to use as an easy thing.",
    language: "CSS",
  },
  {
    full_name: "Developer-Y/cs-video-courses",
    owner: "Developer-Y",
    avatar_url: "https://avatars.githubusercontent.com/u/22699926?v=4",
    stars: 81879,
    description: "List of Computer Science courses with video lectures.",
    language: "",
  },
  {
    full_name: "Stirling-Tools/Stirling-PDF",
    owner: "Stirling-Tools",
    avatar_url: "https://avatars.githubusercontent.com/u/139791695?v=4",
    stars: 81799,
    description:
      "#1 PDF Application on GitHub that lets you edit PDFs on any device anywhere",
    language: "Java",
  },
  {
    full_name: "tonsky/FiraCode",
    owner: "tonsky",
    avatar_url: "https://avatars.githubusercontent.com/u/285292?v=4",
    stars: 81773,
    description: "Free monospaced font with programming ligatures",
    language: "Clojure",
  },
  {
    full_name: "vitejs/vite",
    owner: "vitejs",
    avatar_url: "https://avatars.githubusercontent.com/u/65625612?v=4",
    stars: 81560,
    description: "Next generation frontend tooling. It's fast!",
    language: "TypeScript",
  },
  {
    full_name: "fighting41love/funNLP",
    owner: "fighting41love",
    avatar_url: "https://avatars.githubusercontent.com/u/11475294?v=4",
    stars: 81376,
    description:
      "中英文敏感词、语言检测、中外手机/电话归属地/运营商查询、名字推断性别、手机号抽取、身份证抽取、邮箱抽取、中日文人名库、中文缩写库、拆字词典、词汇情感值、停用词、反动词表、暴恐词表、繁简体转换、英文模拟中文发音、汪峰歌词生成器、职业名称词库、同义词库、反义词库、否定词库、汽车品牌",
    language: "Python",
  },
  {
    full_name: "junegunn/fzf",
    owner: "junegunn",
    avatar_url: "https://avatars.githubusercontent.com/u/700826?v=4",
    stars: 81080,
    description: ":cherry_blossom: A command-line fuzzy finder",
    language: "Go",
  },
  {
    full_name: "spring-projects/spring-boot",
    owner: "spring-projects",
    avatar_url: "https://avatars.githubusercontent.com/u/317776?v=4",
    stars: 80993,
    description:
      "Spring Boot helps you to create Spring-powered, production-grade applications and services with absolute minimum fuss.",
    language: "Java",
  },
  {
    full_name: "mlabonne/llm-course",
    owner: "mlabonne",
    avatar_url: "https://avatars.githubusercontent.com/u/81252890?v=4",
    stars: 80258,
    description:
      "Course to get into Large Language Models (LLMs) with roadmaps and Colab notebooks.",
    language: "",
  },
  {
    full_name: "anuraghazra/github-readme-stats",
    owner: "anuraghazra",
    avatar_url: "https://avatars.githubusercontent.com/u/35374649?v=4",
    stars: 79706,
    description: ":zap: Dynamically generated stats for your github readmes",
    language: "JavaScript",
  },
  {
    full_name: "hoppscotch/hoppscotch",
    owner: "hoppscotch",
    avatar_url: "https://avatars.githubusercontent.com/u/56705483?v=4",
    stars: 79594,
    description:
      "Open-Source API Development Ecosystem • https://hoppscotch.io • Offline, On-Prem & Cloud • Web, Desktop & CLI • Open-Source Alternative to P",
    language: "TypeScript",
  },
  {
    full_name: "jesseduffield/lazygit",
    owner: "jesseduffield",
    avatar_url: "https://avatars.githubusercontent.com/u/8456633?v=4",
    stars: 79467,
    description: "simple terminal UI for git commands",
    language: "Go",
  },
  {
    full_name: "netdata/netdata",
    owner: "netdata",
    avatar_url: "https://avatars.githubusercontent.com/u/43390781?v=4",
    stars: 79332,
    description:
      "The fastest path to AI-powered full stack observability, even for lean teams.",
    language: "Go",
  },
  {
    full_name: "doocs/advanced-java",
    owner: "doocs",
    avatar_url: "https://avatars.githubusercontent.com/u/43716716?v=4",
    stars: 78992,
    description:
      "😮 Core Interview Questions & Answers For Experienced Java(Backend) Developers | 互联网 Java 工程师进阶知识完全扫盲：涵盖高并发、分布式、高可用、微服务、海量数据处理等领域知识",
    language: "Java",
  },
  {
    full_name: "lobehub/lobehub",
    owner: "lobehub",
    avatar_url: "https://avatars.githubusercontent.com/u/131470832?v=4",
    stars: 78912,
    description:
      "🤯 LobeHub is your Chief Agent Operator, organizing your agents into 7×24 operations by hiring, scheduling, and reporting on your entire AI t",
    language: "TypeScript",
  },
  {
    full_name: "swisskyrepo/PayloadsAllTheThings",
    owner: "swisskyrepo",
    avatar_url: "https://avatars.githubusercontent.com/u/12152583?v=4",
    stars: 78561,
    description:
      "A list of useful payloads and bypass for Web Application Security and Pentest/CTF",
    language: "Python",
  },
  {
    full_name: "d2l-ai/d2l-zh",
    owner: "d2l-ai",
    avatar_url: "https://avatars.githubusercontent.com/u/43974506?v=4",
    stars: 78464,
    description:
      "《动手学深度学习》：面向中文读者、能运行、可讨论。中英文版被70多个国家的500多所大学用于教学。",
    language: "Python",
  },
  {
    full_name: "coder/code-server",
    owner: "coder",
    avatar_url: "https://avatars.githubusercontent.com/u/95932066?v=4",
    stars: 77999,
    description: "VS Code in the browser",
    language: "TypeScript",
  },
  {
    full_name: "OpenHands/OpenHands",
    owner: "OpenHands",
    avatar_url: "https://avatars.githubusercontent.com/u/225919603?v=4",
    stars: 77880,
    description: "🙌 OpenHands: AI-Driven Development",
    language: "Python",
  },
  {
    full_name: "Z4nzu/hackingtool",
    owner: "Z4nzu",
    avatar_url: "https://avatars.githubusercontent.com/u/25708027?v=4",
    stars: 77675,
    description: "ALL IN ONE Hacking Tool For Hackers",
    language: "Python",
  },
  {
    full_name: "tensorflow/models",
    owner: "tensorflow",
    avatar_url: "https://avatars.githubusercontent.com/u/15658638?v=4",
    stars: 77668,
    description: "Models and examples built with TensorFlow",
    language: "Python",
  },
  {
    full_name: "nomic-ai/gpt4all",
    owner: "nomic-ai",
    avatar_url: "https://avatars.githubusercontent.com/u/102670180?v=4",
    stars: 77370,
    description:
      "GPT4All: Run Local LLMs on Any Device. Open-source and available for commercial use.",
    language: "C++",
  },
  {
    full_name: "ventoy/Ventoy",
    owner: "ventoy",
    avatar_url: "https://avatars.githubusercontent.com/u/59477474?v=4",
    stars: 77294,
    description: "A new bootable USB solution.",
    language: "C",
  },
  {
    full_name: "elastic/elasticsearch",
    owner: "elastic",
    avatar_url: "https://avatars.githubusercontent.com/u/6764390?v=4",
    stars: 77077,
    description: "Free and Open Source, Distributed, RESTful Search Engine",
    language: "Java",
  },
  {
    full_name: "FortAwesome/Font-Awesome",
    owner: "FortAwesome",
    avatar_url: "https://avatars.githubusercontent.com/u/1505683?v=4",
    stars: 76676,
    description: "The iconic SVG, font, and CSS toolkit",
    language: "JavaScript",
  },
  {
    full_name: "MisterBooo/LeetCodeAnimation",
    owner: "MisterBooo",
    avatar_url: "https://avatars.githubusercontent.com/u/15308811?v=4",
    stars: 76591,
    description:
      "Demonstrate all the questions on LeetCode in the form of animation.（用动画的形式呈现解LeetCode题目的思路）",
    language: "Java",
  },
  {
    full_name: "sdmg15/Best-websites-a-programmer-should-visit",
    owner: "sdmg15",
    avatar_url: "https://avatars.githubusercontent.com/u/13077039?v=4",
    stars: 76162,
    description: ":link: Some useful websites for programmers.",
    language: "",
  },
  {
    full_name: "awesomedata/awesome-public-datasets",
    owner: "awesomedata",
    avatar_url: "https://avatars.githubusercontent.com/u/35111974?v=4",
    stars: 76026,
    description: "A topic-centric list of HQ open datasets.",
    language: "",
  },
  {
    full_name: "nestjs/nest",
    owner: "nestjs",
    avatar_url: "https://avatars.githubusercontent.com/u/28507035?v=4",
    stars: 75916,
    description:
      "A progressive Node.js framework for building efficient, scalable, and enterprise-grade server-side applications with TypeScript/JavaScript 🚀",
    language: "TypeScript",
  },
  {
    full_name: "dair-ai/Prompt-Engineering-Guide",
    owner: "dair-ai",
    avatar_url: "https://avatars.githubusercontent.com/u/30384625?v=4",
    stars: 75804,
    description:
      "🐙 Guides, papers, lessons, notebooks and resources for prompt engineering, context engineering, RAG, and AI Agents.",
    language: "MDX",
  },
  {
    full_name: "typicode/json-server",
    owner: "typicode",
    avatar_url: "https://avatars.githubusercontent.com/u/5502029?v=4",
    stars: 75617,
    description:
      "Get a full fake REST API with zero coding in less than 30 seconds (seriously)",
    language: "JavaScript",
  },
  {
    full_name: "pewdiepie-archdaemon/odysseus",
    owner: "pewdiepie-archdaemon",
    avatar_url: "https://avatars.githubusercontent.com/u/229018391?v=4",
    stars: 75289,
    description: "Self-hosted AI workspace. ",
    language: "Python",
  },
  {
    full_name: "JuliusBrussee/caveman",
    owner: "JuliusBrussee",
    avatar_url: "https://avatars.githubusercontent.com/u/104168679?v=4",
    stars: 75245,
    description:
      "🪨 why use many token when few token do trick — Claude Code skill that cuts 65% of tokens by talking like caveman",
    language: "JavaScript",
  },
  {
    full_name: "redis/redis",
    owner: "redis",
    avatar_url: "https://avatars.githubusercontent.com/u/1529926?v=4",
    stars: 75003,
    description:
      "For developers, who are building real-time data-driven applications, Redis is the preferred, fastest, and most feature-rich cache, data stru",
    language: "C",
  },
  {
    full_name: "ruvnet/RuView",
    owner: "ruvnet",
    avatar_url: "https://avatars.githubusercontent.com/u/2934394?v=4",
    stars: 74884,
    description:
      "π RuView turns commodity WiFi signals into real-time spatial intelligence, vital sign monitoring, and presence detection — all without a sin",
    language: "Rust",
  },
  {
    full_name: "tesseract-ocr/tesseract",
    owner: "tesseract-ocr",
    avatar_url: "https://avatars.githubusercontent.com/u/8401422?v=4",
    stars: 74852,
    description: "Tesseract Open Source OCR Engine (main repository)",
    language: "C++",
  },
  {
    full_name: "grafana/grafana",
    owner: "grafana",
    avatar_url: "https://avatars.githubusercontent.com/u/7195757?v=4",
    stars: 74556,
    description:
      "The open and composable observability and data visualization platform. Visualize metrics, logs, and traces from multiple sources like Promet",
    language: "TypeScript",
  },
  {
    full_name: "TapXWorld/ChinaTextbook",
    owner: "TapXWorld",
    avatar_url: "https://avatars.githubusercontent.com/u/3353541?v=4",
    stars: 74412,
    description: "所有小初高、大学PDF教材。",
    language: "Roff",
  },
  {
    full_name: "openai/openai-cookbook",
    owner: "openai",
    avatar_url: "https://avatars.githubusercontent.com/u/14957082?v=4",
    stars: 74284,
    description: "Examples and guides for using the OpenAI API",
    language: "Jupyter Notebook",
  },
  {
    full_name: "ocornut/imgui",
    owner: "ocornut",
    avatar_url: "https://avatars.githubusercontent.com/u/8225057?v=4",
    stars: 73982,
    description:
      "Dear ImGui: Bloat-free Graphical User interface for C++ with minimal dependencies",
    language: "C++",
  },
  {
    full_name: "unionlabs/union",
    owner: "unionlabs",
    avatar_url: "https://avatars.githubusercontent.com/u/129756567?v=4",
    stars: 73951,
    description:
      "The trust-minimized, zero-knowledge bridging protocol, designed for censorship resistance, extremely high security, and usage in decentraliz",
    language: "Rust",
  },
  {
    full_name: "enaqx/awesome-react",
    owner: "enaqx",
    avatar_url: "https://avatars.githubusercontent.com/u/182219?v=4",
    stars: 73703,
    description: "A collection of awesome things regarding React ecosystem",
    language: "",
  },
  {
    full_name: "vuejs/awesome-vue",
    owner: "vuejs",
    avatar_url: "https://avatars.githubusercontent.com/u/6128107?v=4",
    stars: 73563,
    description: "🎉 A curated list of awesome things related to Vue.js",
    language: "",
  },
  {
    full_name: "twitter/the-algorithm",
    owner: "twitter",
    avatar_url: "https://avatars.githubusercontent.com/u/50278?v=4",
    stars: 73455,
    description: "Source code for the X Recommendation Algorithm",
    language: "Scala",
  },
  {
    full_name: "caddyserver/caddy",
    owner: "caddyserver",
    avatar_url: "https://avatars.githubusercontent.com/u/12955528?v=4",
    stars: 73454,
    description:
      "Fast and extensible multi-platform HTTP/1-2-3 web server with automatic HTTPS",
    language: "Go",
  },
  {
    full_name: "apache/superset",
    owner: "apache",
    avatar_url: "https://avatars.githubusercontent.com/u/47359?v=4",
    stars: 73409,
    description:
      "Apache Superset is a Data Visualization and Data Exploration Platform",
    language: "TypeScript",
  },
  {
    full_name: "obsproject/obs-studio",
    owner: "obsproject",
    avatar_url: "https://avatars.githubusercontent.com/u/7725691?v=4",
    stars: 73333,
    description:
      "OBS Studio - Free and open source software for live streaming and screen recording",
    language: "C",
  },
  {
    full_name: "python/cpython",
    owner: "python",
    avatar_url: "https://avatars.githubusercontent.com/u/1525981?v=4",
    stars: 73329,
    description: "The Python programming language",
    language: "Python",
  },
  {
    full_name: "PKUFlyingPig/cs-self-learning",
    owner: "PKUFlyingPig",
    avatar_url: "https://avatars.githubusercontent.com/u/60659728?v=4",
    stars: 73271,
    description: "计算机自学指南",
    language: "HTML",
  },
  {
    full_name: "CompVis/stable-diffusion",
    owner: "CompVis",
    avatar_url: "https://avatars.githubusercontent.com/u/30233788?v=4",
    stars: 73129,
    description: "A latent text-to-image diffusion model",
    language: "Jupyter Notebook",
  },
  {
    full_name: "abi/screenshot-to-code",
    owner: "abi",
    avatar_url: "https://avatars.githubusercontent.com/u/23818?v=4",
    stars: 72998,
    description:
      "Drop in a screenshot and convert it to clean code (HTML/Tailwind/React/Vue)",
    language: "Python",
  },
  {
    full_name: "thedaviddias/Front-End-Checklist",
    owner: "thedaviddias",
    avatar_url: "https://avatars.githubusercontent.com/u/237229?v=4",
    stars: 72987,
    description:
      "🗂 The essential checklist for modern web development, for humans and AI agents",
    language: "MDX",
  },
  {
    full_name: "josephmisiti/awesome-machine-learning",
    owner: "josephmisiti",
    avatar_url: "https://avatars.githubusercontent.com/u/246302?v=4",
    stars: 72975,
    description:
      "A curated list of awesome Machine Learning frameworks, libraries and software.",
    language: "Python",
  },
  {
    full_name: "AppFlowy-IO/AppFlowy",
    owner: "AppFlowy-IO",
    avatar_url: "https://avatars.githubusercontent.com/u/86002201?v=4",
    stars: 72718,
    description:
      "Bring projects, wikis, and teams together with AI. AppFlowy is the AI collaborative workspace where you achieve more without losing control ",
    language: "Dart",
  },
  {
    full_name: "strapi/strapi",
    owner: "strapi",
    avatar_url: "https://avatars.githubusercontent.com/u/19872173?v=4",
    stars: 72418,
    description:
      "🚀 Strapi is the leading open-source headless CMS. It’s 100% JavaScript/TypeScript, fully customizable, and developer-first.",
    language: "TypeScript",
  },
  {
    full_name: "daytonaio/daytona",
    owner: "daytonaio",
    avatar_url: "https://avatars.githubusercontent.com/u/130513197?v=4",
    stars: 72379,
    description:
      "Daytona is a Secure and Elastic Infrastructure for Running AI-Generated Code",
    language: "TypeScript",
  },
  {
    full_name: "hiyouga/LlamaFactory",
    owner: "hiyouga",
    avatar_url: "https://avatars.githubusercontent.com/u/16256802?v=4",
    stars: 72316,
    description: "Unified Efficient Fine-Tuning of 100+ LLMs & VLMs (ACL 2024)",
    language: "Python",
  },
  {
    full_name: "Eugeny/tabby",
    owner: "Eugeny",
    avatar_url: "https://avatars.githubusercontent.com/u/161476?v=4",
    stars: 72250,
    description: "A terminal for a more modern age",
    language: "TypeScript",
  },
  {
    full_name: "bytedance/deer-flow",
    owner: "bytedance",
    avatar_url: "https://avatars.githubusercontent.com/u/4158466?v=4",
    stars: 72170,
    description:
      "An open-source long-horizon SuperAgent harness that researches, codes, and creates. With the help of sandboxes, memories, tools, skill, suba",
    language: "Python",
  },
  {
    full_name: "binhnguyennus/awesome-scalability",
    owner: "binhnguyennus",
    avatar_url: "https://avatars.githubusercontent.com/u/15001306?v=4",
    stars: 71928,
    description:
      "The Patterns of Scalable, Reliable, and Performant Large-Scale Systems",
    language: "",
  },
  {
    full_name: "fffaraz/awesome-cpp",
    owner: "fffaraz",
    avatar_url: "https://avatars.githubusercontent.com/u/895678?v=4",
    stars: 71890,
    description:
      "A curated list of awesome C++ (or C) frameworks, libraries, resources, and shiny things. Inspired by awesome-... stuff.",
    language: "",
  },
  {
    full_name: "hakimel/reveal.js",
    owner: "hakimel",
    avatar_url: "https://avatars.githubusercontent.com/u/629429?v=4",
    stars: 71777,
    description: "The HTML Presentation Framework",
    language: "JavaScript",
  },
  {
    full_name: "moby/moby",
    owner: "moby",
    avatar_url: "https://avatars.githubusercontent.com/u/27259197?v=4",
    stars: 71717,
    description:
      "The Moby Project - a collaborative project for the container ecosystem to assemble container-based systems",
    language: "Go",
  },
  {
    full_name: "pallets/flask",
    owner: "pallets",
    avatar_url: "https://avatars.githubusercontent.com/u/16748505?v=4",
    stars: 71683,
    description: "The Python micro framework for building web applications.",
    language: "Python",
  },
  {
    full_name: "danielmiessler/SecLists",
    owner: "danielmiessler",
    avatar_url: "https://avatars.githubusercontent.com/u/50654?v=4",
    stars: 71658,
    description:
      "SecLists is the security tester's companion. It's a collection of multiple types of lists used during security assessments, collected in one",
    language: "PHP",
  },
  {
    full_name: "protocolbuffers/protobuf",
    owner: "protocolbuffers",
    avatar_url: "https://avatars.githubusercontent.com/u/26310541?v=4",
    stars: 71372,
    description: "Protocol Buffers - Google's data interchange format",
    language: "C++",
  },
  {
    full_name: "paperclipai/paperclip",
    owner: "paperclipai",
    avatar_url: "https://avatars.githubusercontent.com/u/264498616?v=4",
    stars: 71111,
    description: "The open-source app everyone uses to manage agents at work",
    language: "TypeScript",
  },
  {
    full_name: "binary-husky/gpt_academic",
    owner: "binary-husky",
    avatar_url: "https://avatars.githubusercontent.com/u/96192199?v=4",
    stars: 70900,
    description:
      "为GPT/GLM等LLM大语言模型提供实用化交互接口，特别优化论文阅读/润色/写作体验，模块化设计，支持自定义快捷按钮&函数插件，支持Python和C++等项目剖析&自译解功能，PDF/LaTex论文翻译&总结功能，支持并行问询多种LLM模型，支持chatglm3等本地模型。接入",
    language: "Python",
  },
  {
    full_name: "nektos/act",
    owner: "nektos",
    avatar_url: "https://avatars.githubusercontent.com/u/3813618?v=4",
    stars: 70821,
    description: "Run your GitHub Actions locally 🚀",
    language: "Go",
  },
  {
    full_name: "swiftlang/swift",
    owner: "swiftlang",
    avatar_url: "https://avatars.githubusercontent.com/u/42816656?v=4",
    stars: 70083,
    description: "The Swift Programming Language",
    language: "Swift",
  },
  {
    full_name: "safishamsi/graphify",
    owner: "safishamsi",
    avatar_url: "https://avatars.githubusercontent.com/u/216348667?v=4",
    stars: 70033,
    description:
      "AI coding assistant skill (Claude Code, Codex, OpenCode, Cursor, Gemini CLI, and more). Turn any folder of code, SQL schemas, R scripts, she",
    language: "Python",
  },
  {
    full_name: "juliangarnier/anime",
    owner: "juliangarnier",
    avatar_url: "https://avatars.githubusercontent.com/u/1268691?v=4",
    stars: 70011,
    description: "JavaScript animation engine",
    language: "JavaScript",
  },
  {
    full_name: "NationalSecurityAgency/ghidra",
    owner: "NationalSecurityAgency",
    avatar_url: "https://avatars.githubusercontent.com/u/11298292?v=4",
    stars: 69956,
    description: "Ghidra is a software reverse engineering (SRE) framework",
    language: "Java",
  },
  {
    full_name: "toeverything/AFFiNE",
    owner: "toeverything",
    avatar_url: "https://avatars.githubusercontent.com/u/78728988?v=4",
    stars: 69620,
    description:
      "There can be more than Notion and Miro. AFFiNE(pronounced [ə‘fain]) is a next-gen knowledge base that brings planning, sorting and creating ",
    language: "TypeScript",
  },
  {
    full_name: "OpenBB-finance/OpenBB",
    owner: "OpenBB-finance",
    avatar_url: "https://avatars.githubusercontent.com/u/80064875?v=4",
    stars: 69484,
    description: "Financial data platform for analysts, quants and AI agents.",
    language: "Python",
  },
  {
    full_name: "expressjs/express",
    owner: "expressjs",
    avatar_url: "https://avatars.githubusercontent.com/u/5658226?v=4",
    stars: 69215,
    description: "Fast, unopinionated, minimalist web framework for node.",
    language: "JavaScript",
  },
  {
    full_name: "prakhar1989/awesome-courses",
    owner: "prakhar1989",
    avatar_url: "https://avatars.githubusercontent.com/u/649249?v=4",
    stars: 69212,
    description:
      ":books: List of awesome university courses for learning Computer Science!",
    language: "",
  },
  {
    full_name: "unclecode/crawl4ai",
    owner: "unclecode",
    avatar_url: "https://avatars.githubusercontent.com/u/12494079?v=4",
    stars: 69051,
    description:
      "🚀🤖 Crawl4AI: Open-source LLM Friendly Web Crawler & Scraper. Don't be shy, join here: https://discord.gg/jP8KfhDhyN",
    language: "Python",
  },
  {
    full_name: "ansible/ansible",
    owner: "ansible",
    avatar_url: "https://avatars.githubusercontent.com/u/1507452?v=4",
    stars: 69006,
    description:
      "Ansible is a radically simple IT automation platform that makes your applications and systems easier to deploy and maintain. Automate everyt",
    language: "Python",
  },
  {
    full_name: "FoundationAgents/MetaGPT",
    owner: "FoundationAgents",
    avatar_url: "https://avatars.githubusercontent.com/u/198047230?v=4",
    stars: 68934,
    description:
      "🌟 The Multi-Agent Framework: First AI Software Company, Towards Natural Language Programming",
    language: "Python",
  },
  {
    full_name: "base/node",
    owner: "base",
    avatar_url: "https://avatars.githubusercontent.com/u/16627100?v=4",
    stars: 68516,
    description: "Everything required to run your own Base node",
    language: "Shell",
  },
  {
    full_name: "nexu-io/open-design",
    owner: "nexu-io",
    avatar_url: "https://avatars.githubusercontent.com/u/263625318?v=4",
    stars: 68363,
    description:
      "🎨 Local-first, open-source Claude Design alternative. 🖥️ Native desktop app. ⚡ 259+ Skills · ✨ 142+ Design Systems 🖼️ Web · desktop · mobile",
    language: "TypeScript",
  },
  {
    full_name: "opendatalab/MinerU",
    owner: "opendatalab",
    avatar_url: "https://avatars.githubusercontent.com/u/97503431?v=4",
    stars: 68173,
    description:
      "Transforms complex documents like PDFs and Office docs into LLM-ready markdown/JSON for your Agentic workflows.",
    language: "Python",
  },
  {
    full_name: "chrislgarry/Apollo-11",
    owner: "chrislgarry",
    avatar_url: "https://avatars.githubusercontent.com/u/2200898?v=4",
    stars: 68112,
    description:
      "Original Apollo 11 Guidance Computer (AGC) source code for the command and lunar modules.",
    language: "Assembly",
  },
  {
    full_name: "microsoft/ai-agents-for-beginners",
    owner: "microsoft",
    avatar_url: "https://avatars.githubusercontent.com/u/6154722?v=4",
    stars: 67643,
    description: "12 Lessons to Get Started Building AI Agents",
    language: "Jupyter Notebook",
  },
  {
    full_name: "shareAI-lab/learn-claude-code",
    owner: "shareAI-lab",
    avatar_url: "https://avatars.githubusercontent.com/u/189210346?v=4",
    stars: 67617,
    description:
      "Bash is all you need -  A nano claude code–like 「agent harness」, built from 0 to 1",
    language: "Python",
  },
  {
    full_name: "chartjs/Chart.js",
    owner: "chartjs",
    avatar_url: "https://avatars.githubusercontent.com/u/10342521?v=4",
    stars: 67515,
    description: "Simple HTML5 Charts using the <canvas> tag",
    language: "JavaScript",
  },
  {
    full_name: "unslothai/unsloth",
    owner: "unslothai",
    avatar_url: "https://avatars.githubusercontent.com/u/150920049?v=4",
    stars: 66994,
    description:
      "Unsloth Studio is a web UI for training and running open models like Gemma 4, Qwen3.6, DeepSeek, gpt-oss locally.",
    language: "Python",
  },
  {
    full_name: "labmlai/annotated_deep_learning_paper_implementations",
    owner: "labmlai",
    avatar_url: "https://avatars.githubusercontent.com/u/64068543?v=4",
    stars: 66979,
    description:
      "🧑‍🏫 60+ Implementations/tutorials of deep learning papers with side-by-side notes 📝; including transformers (original, xl, switch, feedback,",
    language: "Python",
  },
  {
    full_name: "666ghj/MiroFish",
    owner: "666ghj",
    avatar_url: "https://avatars.githubusercontent.com/u/110395318?v=4",
    stars: 66893,
    description:
      "A Simple and Universal Swarm Intelligence Engine, Predicting Anything. 简洁通用的群体智能引擎，预测万物",
    language: "Python",
  },
  {
    full_name: "apache/echarts",
    owner: "apache",
    avatar_url: "https://avatars.githubusercontent.com/u/47359?v=4",
    stars: 66622,
    description:
      "Apache ECharts is a powerful, interactive charting and data visualization library for browser",
    language: "TypeScript",
  },
  {
    full_name: "leonardomso/33-js-concepts",
    owner: "leonardomso",
    avatar_url: "https://avatars.githubusercontent.com/u/8030067?v=4",
    stars: 66476,
    description: "📜 33 JavaScript concepts every developer should know.",
    language: "JavaScript",
  },
  {
    full_name: "xtekky/gpt4free",
    owner: "xtekky",
    avatar_url: "https://avatars.githubusercontent.com/u/98614666?v=4",
    stars: 66392,
    description:
      "The official gpt4free repository | various collection of powerful language models | opus 4.6 gpt 5.3 kimi 2.5 deepseek v3.2 gemini 3",
    language: "Python",
  },
  {
    full_name: "scikit-learn/scikit-learn",
    owner: "scikit-learn",
    avatar_url: "https://avatars.githubusercontent.com/u/365630?v=4",
    stars: 66378,
    description: "scikit-learn: machine learning in Python",
    language: "Python",
  },
  {
    full_name: "bradtraversy/design-resources-for-developers",
    owner: "bradtraversy",
    avatar_url: "https://avatars.githubusercontent.com/u/5550850?v=4",
    stars: 66162,
    description:
      "Curated list of design and UI resources from stock photos, web templates, CSS frameworks, UI libraries, tools and much more",
    language: "",
  },
  {
    full_name: "sindresorhus/awesome-nodejs",
    owner: "sindresorhus",
    avatar_url: "https://avatars.githubusercontent.com/u/170270?v=4",
    stars: 66018,
    description:
      ":zap: Delightful Node.js packages and resources [BECAUSE OF TOO MUCH SPAM AND LOW-QUALITY SUBMISSIONS, SUBMISSIONS ARE PAUSED UNTIL JULY]",
    language: "",
  },
  {
    full_name: "TheAlgorithms/Java",
    owner: "TheAlgorithms",
    avatar_url: "https://avatars.githubusercontent.com/u/20487725?v=4",
    stars: 65861,
    description: "All Algorithms implemented in Java",
    language: "Java",
  },
  {
    full_name: "webpack/webpack",
    owner: "webpack",
    avatar_url: "https://avatars.githubusercontent.com/u/2105791?v=4",
    stars: 65848,
    description:
      "A bundler for javascript and friends. Packs many modules into a few bundled assets. Code Splitting allows for loading parts of the applicati",
    language: "JavaScript",
  },
  {
    full_name: "Asabeneh/30-Days-Of-Python",
    owner: "Asabeneh",
    avatar_url: "https://avatars.githubusercontent.com/u/9008063?v=4",
    stars: 65661,
    description:
      "The 30 Days of Python programming challenge is a step-by-step guide to learn the Python programming language in 30 days. This challenge may ",
    language: "Python",
  },
  {
    full_name: "gorhill/uBlock",
    owner: "gorhill",
    avatar_url: "https://avatars.githubusercontent.com/u/585534?v=4",
    stars: 65652,
    description:
      "uBlock Origin - An efficient blocker for Chromium and Firefox. Fast and lean.",
    language: "JavaScript",
  },
  {
    full_name: "kelseyhightower/nocode",
    owner: "kelseyhightower",
    avatar_url: "https://avatars.githubusercontent.com/u/1123322?v=4",
    stars: 65416,
    description:
      "The best way to write secure and reliable applications. Write nothing; deploy nowhere.",
    language: "Dockerfile",
  },
  {
    full_name: "ComposioHQ/awesome-claude-skills",
    owner: "ComposioHQ",
    avatar_url: "https://avatars.githubusercontent.com/u/128464815?v=4",
    stars: 65383,
    description:
      "A curated list of awesome Claude Skills, resources, and tools for customizing Claude AI workflows",
    language: "Python",
  },
  {
    full_name: "lydiahallie/javascript-questions",
    owner: "lydiahallie",
    avatar_url: "https://avatars.githubusercontent.com/u/29451794?v=4",
    stars: 65318,
    description:
      "A long list of (advanced) JavaScript questions, and their explanations :sparkles:  ",
    language: "",
  },
  {
    full_name: "facebook/docusaurus",
    owner: "facebook",
    avatar_url: "https://avatars.githubusercontent.com/u/69631?v=4",
    stars: 65307,
    description: "Easy to maintain open source documentation websites.",
    language: "TypeScript",
  },
  {
    full_name: "BurntSushi/ripgrep",
    owner: "BurntSushi",
    avatar_url: "https://avatars.githubusercontent.com/u/456674?v=4",
    stars: 65282,
    description:
      "ripgrep recursively searches directories for a regex pattern while respecting your gitignore",
    language: "Rust",
  },
  {
    full_name: "D4Vinci/Scrapling",
    owner: "D4Vinci",
    avatar_url: "https://avatars.githubusercontent.com/u/20604835?v=4",
    stars: 65275,
    description:
      "🕷️ An adaptive Web Scraping framework that handles everything from a single request to a full-scale crawl!",
    language: "Python",
  },
  {
    full_name: "localstack/localstack",
    owner: "localstack",
    avatar_url: "https://avatars.githubusercontent.com/u/28732122?v=4",
    stars: 65067,
    description:
      "💻 A fully functional local AWS cloud stack. Develop and test your cloud & Serverless apps offline",
    language: "Python",
  },
  {
    full_name: "kdn251/interviews",
    owner: "kdn251",
    avatar_url: "https://avatars.githubusercontent.com/u/16903644?v=4",
    stars: 64991,
    description: "Everything you need to know to get the job.",
    language: "Java",
  },
  {
    full_name: "Egonex-AI/Understand-Anything",
    owner: "Egonex-AI",
    avatar_url: "https://avatars.githubusercontent.com/u/257477979?v=4",
    stars: 64849,
    description:
      "Graphs that teach > graphs that impress. Turn any code into an interactive knowledge graph you can explore, search, and ask questions about.",
    language: "TypeScript",
  },
  {
    full_name: "prometheus/prometheus",
    owner: "prometheus",
    avatar_url: "https://avatars.githubusercontent.com/u/3380462?v=4",
    stars: 64646,
    description: "The Prometheus monitoring system and time series database.",
    language: "Go",
  },
  {
    full_name: "alacritty/alacritty",
    owner: "alacritty",
    avatar_url: "https://avatars.githubusercontent.com/u/29714349?v=4",
    stars: 64627,
    description: "A cross-platform, OpenGL terminal emulator.",
    language: "Rust",
  },
  {
    full_name: "addyosmani/agent-skills",
    owner: "addyosmani",
    avatar_url: "https://avatars.githubusercontent.com/u/110953?v=4",
    stars: 64409,
    description: "Production-grade engineering skills for AI coding agents.",
    language: "Shell",
  },
  {
    full_name: "gsd-build/get-shit-done",
    owner: "gsd-build",
    avatar_url: "https://avatars.githubusercontent.com/u/260490621?v=4",
    stars: 64408,
    description:
      "A light-weight and powerful meta-prompting, context engineering and spec-driven development system for Claude Code by TÂCHES.",
    language: "JavaScript",
  },
  {
    full_name: "earendil-works/pi",
    owner: "earendil-works",
    avatar_url: "https://avatars.githubusercontent.com/u/207902832?v=4",
    stars: 64344,
    description:
      "AI agent toolkit: unified LLM API, agent loop, TUI, coding agent CLI",
    language: "TypeScript",
  },
  {
    full_name: "rtk-ai/rtk",
    owner: "rtk-ai",
    avatar_url: "https://avatars.githubusercontent.com/u/258253854?v=4",
    stars: 64328,
    description:
      "CLI proxy that reduces LLM token consumption by 60-90% on common dev commands. Single Rust binary, zero dependencies",
    language: "Rust",
  },
  {
    full_name: "LadybirdBrowser/ladybird",
    owner: "LadybirdBrowser",
    avatar_url: "https://avatars.githubusercontent.com/u/134672918?v=4",
    stars: 64177,
    description: "Truly independent web browser",
    language: "C++",
  },
  {
    full_name: "keras-team/keras",
    owner: "keras-team",
    avatar_url: "https://avatars.githubusercontent.com/u/34455048?v=4",
    stars: 64095,
    description: "Deep Learning for humans",
    language: "Python",
  },
  {
    full_name: "openinterpreter/openinterpreter",
    owner: "openinterpreter",
    avatar_url: "https://avatars.githubusercontent.com/u/163192481?v=4",
    stars: 64072,
    description:
      "A lightweight coding agent for open models like Deepseek, Kimi, and Qwen",
    language: "Rust",
  },
  {
    full_name: "traefik/traefik",
    owner: "traefik",
    avatar_url: "https://avatars.githubusercontent.com/u/14280338?v=4",
    stars: 63694,
    description: "The Cloud Native Application Proxy",
    language: "Go",
  },
  {
    full_name: "cline/cline",
    owner: "cline",
    avatar_url: "https://avatars.githubusercontent.com/u/184127137?v=4",
    stars: 63591,
    description:
      "Autonomous coding agent as an SDK, IDE extension, or CLI assistant.",
    language: "TypeScript",
  },
  {
    full_name: "nocodb/nocodb",
    owner: "nocodb",
    avatar_url: "https://avatars.githubusercontent.com/u/50206778?v=4",
    stars: 63501,
    description: "🔥 🔥 🔥 A Free & Self-hostable Airtable Alternative",
    language: "TypeScript",
  },
  {
    full_name: "ryanoasis/nerd-fonts",
    owner: "ryanoasis",
    avatar_url: "https://avatars.githubusercontent.com/u/8083459?v=4",
    stars: 63434,
    description:
      "Iconic font aggregator, collection, & patcher. 3,600+ icons, 50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font Awesome",
    language: "CSS",
  },
  {
    full_name: "rust-lang/rustlings",
    owner: "rust-lang",
    avatar_url: "https://avatars.githubusercontent.com/u/5430905?v=4",
    stars: 63299,
    description:
      ":crab: Small exercises to get you used to reading and writing Rust code!",
    language: "Rust",
  },
  {
    full_name: "socketio/socket.io",
    owner: "socketio",
    avatar_url: "https://avatars.githubusercontent.com/u/10566080?v=4",
    stars: 63186,
    description:
      "Bidirectional and low-latency communication for every platform",
    language: "TypeScript",
  },
  {
    full_name: "code-yeongyu/oh-my-openagent",
    owner: "code-yeongyu",
    avatar_url: "https://avatars.githubusercontent.com/u/11153873?v=4",
    stars: 63100,
    description:
      "omo/lazycodex: The coding agent for tokenmaxxers;the one and only agent harness for complex codebases. For your Codex, for your OpenCode",
    language: "TypeScript",
  },
  {
    full_name: "tldr-pages/tldr",
    owner: "tldr-pages",
    avatar_url: "https://avatars.githubusercontent.com/u/7366472?v=4",
    stars: 62905,
    description: "Collaborative cheatsheets for console commands 📚.",
    language: "Markdown",
  },
  {
    full_name: "pathwaycom/pathway",
    owner: "pathwaycom",
    avatar_url: "https://avatars.githubusercontent.com/u/25750857?v=4",
    stars: 62889,
    description:
      "Python ETL framework for stream processing, real-time analytics, LLM pipelines, and RAG.",
    language: "Python",
  },
  {
    full_name: "resume/resume.github.com",
    owner: "resume",
    avatar_url: "https://avatars.githubusercontent.com/u/602612?v=4",
    stars: 62863,
    description: "Resumes generated using the GitHub informations",
    language: "JavaScript",
  },
  {
    full_name: "dani-garcia/vaultwarden",
    owner: "dani-garcia",
    avatar_url: "https://avatars.githubusercontent.com/u/725423?v=4",
    stars: 62639,
    description:
      "Unofficial Bitwarden compatible server written in Rust, formerly known as bitwarden_rs",
    language: "Rust",
  },
  {
    full_name: "scrapy/scrapy",
    owner: "scrapy",
    avatar_url: "https://avatars.githubusercontent.com/u/733635?v=4",
    stars: 62364,
    description:
      "Scrapy, a fast high-level web crawling & scraping framework for Python.",
    language: "Python",
  },
]
